-- The Fullstack Guys: private, server-side CRM, chat and analytics schema.
-- All writes and reads go through the application's server routes.

create extension if not exists pgcrypto;

create table if not exists public.fullstack_visitors (
  visitor_id uuid primary key,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  first_landing_page text,
  last_page text,
  first_referrer text,
  initial_utm jsonb not null default '{}'::jsonb,
  sessions_count integer not null default 0,
  user_agent text,
  locale text,
  timezone text,
  device jsonb not null default '{}'::jsonb
);

create table if not exists public.fullstack_sessions (
  session_id uuid primary key,
  visitor_id uuid not null references public.fullstack_visitors(visitor_id) on delete cascade,
  started_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  ended_at timestamptz,
  landing_page text,
  current_page text,
  referrer text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_term text,
  utm_content text,
  user_agent text,
  locale text,
  timezone text,
  device_type text,
  screen_width integer,
  screen_height integer,
  viewport_width integer,
  viewport_height integer,
  ip_hash text,
  country text,
  region text,
  city text,
  event_count integer not null default 0,
  click_count integer not null default 0,
  max_scroll_depth integer not null default 0,
  duration_ms bigint not null default 0,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.fullstack_analytics_events (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  received_at timestamptz not null default now(),
  session_id uuid references public.fullstack_sessions(session_id) on delete cascade,
  visitor_id uuid references public.fullstack_visitors(visitor_id) on delete cascade,
  event_type text not null,
  path text,
  page_title text,
  referrer text,
  x integer,
  y integer,
  scroll_depth integer,
  viewport_width integer,
  viewport_height integer,
  element text,
  element_text text,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.fullstack_chat_sessions (
  id uuid primary key,
  visitor_id uuid references public.fullstack_visitors(visitor_id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  source_page text,
  user_agent text,
  visitor_name text,
  visitor_email text,
  visitor_phone text,
  company text,
  niche text,
  budget text,
  timeline text,
  project_type text,
  lead_score integer,
  intent text,
  status text not null default 'bot',
  human_joined boolean not null default false,
  last_message text,
  constraint fullstack_chat_status_check check (status in ('bot', 'human', 'closed')),
  constraint fullstack_chat_score_check check (lead_score is null or lead_score between 0 and 100)
);

create table if not exists public.fullstack_chat_messages (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.fullstack_chat_sessions(id) on delete cascade,
  created_at timestamptz not null default now(),
  role text not null,
  content text not null,
  provider text,
  model text,
  metadata jsonb not null default '{}'::jsonb,
  constraint fullstack_chat_role_check check (role in ('user', 'assistant', 'admin', 'system'))
);

create table if not exists public.fullstack_leads (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  visitor_id uuid references public.fullstack_visitors(visitor_id) on delete set null,
  session_id uuid references public.fullstack_sessions(session_id) on delete set null,
  chat_session_id uuid references public.fullstack_chat_sessions(id) on delete set null,
  capture_source text not null default 'chat',
  name text,
  email text,
  phone text,
  company text,
  niche text,
  budget text,
  timeline text,
  project_type text,
  lead_score integer,
  intent text,
  status text not null default 'new',
  summary text,
  transcript jsonb not null default '[]'::jsonb,
  source_page text,
  user_agent text,
  hf_intent text,
  consent_context text,
  metadata jsonb not null default '{}'::jsonb,
  constraint fullstack_lead_score_check check (lead_score is null or lead_score between 0 and 100)
);

create table if not exists public.fullstack_ai_runs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  chat_session_id uuid references public.fullstack_chat_sessions(id) on delete set null,
  provider text not null,
  model text,
  purpose text not null,
  status text not null,
  latency_ms integer,
  input_chars integer,
  output_chars integer,
  error_code text,
  metadata jsonb not null default '{}'::jsonb,
  constraint fullstack_ai_status_check check (status in ('success', 'fallback', 'error', 'timeout'))
);

create table if not exists public.fullstack_admin_actions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  admin_email text not null,
  action text not null,
  chat_session_id uuid references public.fullstack_chat_sessions(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.fullstack_admin_sessions (
  token_hash text primary key,
  email text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create index if not exists fullstack_visitors_last_seen_idx on public.fullstack_visitors (last_seen_at desc);
create index if not exists fullstack_sessions_visitor_idx on public.fullstack_sessions (visitor_id, last_seen_at desc);
create index if not exists fullstack_sessions_last_seen_idx on public.fullstack_sessions (last_seen_at desc);
create index if not exists fullstack_events_session_idx on public.fullstack_analytics_events (session_id, occurred_at);
create index if not exists fullstack_events_visitor_idx on public.fullstack_analytics_events (visitor_id, occurred_at desc);
create index if not exists fullstack_events_type_idx on public.fullstack_analytics_events (event_type, occurred_at desc);
create index if not exists fullstack_events_path_idx on public.fullstack_analytics_events (path, occurred_at desc);
create index if not exists fullstack_chat_messages_session_idx on public.fullstack_chat_messages (session_id, created_at);
create index if not exists fullstack_chat_sessions_updated_idx on public.fullstack_chat_sessions (updated_at desc);
create index if not exists fullstack_chat_sessions_visitor_idx on public.fullstack_chat_sessions (visitor_id, updated_at desc);
create index if not exists fullstack_leads_created_idx on public.fullstack_leads (created_at desc);
create index if not exists fullstack_leads_status_idx on public.fullstack_leads (status, created_at desc);
create index if not exists fullstack_leads_visitor_idx on public.fullstack_leads (visitor_id, created_at desc);
create index if not exists fullstack_leads_session_idx on public.fullstack_leads (session_id, created_at desc);
create index if not exists fullstack_leads_chat_session_idx on public.fullstack_leads (chat_session_id, created_at desc);
create index if not exists fullstack_ai_runs_created_idx on public.fullstack_ai_runs (created_at desc);
create index if not exists fullstack_ai_runs_chat_session_idx on public.fullstack_ai_runs (chat_session_id, created_at desc);
create index if not exists fullstack_admin_actions_chat_session_idx on public.fullstack_admin_actions (chat_session_id, created_at desc);
create index if not exists fullstack_admin_sessions_expires_idx on public.fullstack_admin_sessions (expires_at);

alter table public.fullstack_visitors enable row level security;
alter table public.fullstack_sessions enable row level security;
alter table public.fullstack_analytics_events enable row level security;
alter table public.fullstack_chat_sessions enable row level security;
alter table public.fullstack_chat_messages enable row level security;
alter table public.fullstack_leads enable row level security;
alter table public.fullstack_ai_runs enable row level security;
alter table public.fullstack_admin_actions enable row level security;
alter table public.fullstack_admin_sessions enable row level security;

revoke all on table public.fullstack_visitors from anon, authenticated;
revoke all on table public.fullstack_sessions from anon, authenticated;
revoke all on table public.fullstack_analytics_events from anon, authenticated;
revoke all on table public.fullstack_chat_sessions from anon, authenticated;
revoke all on table public.fullstack_chat_messages from anon, authenticated;
revoke all on table public.fullstack_leads from anon, authenticated;
revoke all on table public.fullstack_ai_runs from anon, authenticated;
revoke all on table public.fullstack_admin_actions from anon, authenticated;
revoke all on table public.fullstack_admin_sessions from anon, authenticated;

grant select, insert, update, delete on table public.fullstack_visitors to service_role;
grant select, insert, update, delete on table public.fullstack_sessions to service_role;
grant select, insert, update, delete on table public.fullstack_analytics_events to service_role;
grant select, insert, update, delete on table public.fullstack_chat_sessions to service_role;
grant select, insert, update, delete on table public.fullstack_chat_messages to service_role;
grant select, insert, update, delete on table public.fullstack_leads to service_role;
grant select, insert, update, delete on table public.fullstack_ai_runs to service_role;
grant select, insert, update, delete on table public.fullstack_admin_actions to service_role;
grant select, insert, update, delete on table public.fullstack_admin_sessions to service_role;
grant usage, select on all sequences in schema public to service_role;
